name: test print
on:
  pull_request:
    types: [ opened, reopened, synchronize, labeled, unlabeled, closed ]
    paths:
      - 'a'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Success!"

