name: test print
on:
  push:
    paths:
      - 'a'
      - '.github/test-requirement-1.yml'
  pull_request:
    types: [ opened, reopened, synchronize, labeled, unlabeled, closed ]
    paths:
      - 'a'
      - '.github/test-requirement-1.yml'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Success!"
      - name: test shorthand if else
        run: echo hi [[ ${{ github.event_name }} == 'pull_request' ]] && echo 'pull_request' || echo 'not pull_request' }}